$(function(){
	//头部
	$("#header").load("html/header.html");
<<<<<<< HEAD
	//查询
	$("#search_byAuthor").load("html/search_author.html");
	$("#stu_search").load("html/stu_search.html");
	//通过id查找书
	$("#sear_byBookId").click(function(){
		$("#cont").load("html/search_id.html");
	})
	//通过书名查找书
	$("#sear_byBookName").click(function(){
		$("#cont").load("html/search_byName.html");
	})
	//通过类别查找书
	$("#sear_byBookSort").click(function(){
		$("#cont").load("html/search_byBookSort.html");
	})
=======
	
>>>>>>> a793144b682509faf7335a9d1f73b90b847a39c3
	//修改
	$("#edit").click(function(){
		$("#cont").load("html/student.html");
	})
	//图书状态审核
	$("#checkStatus").click(function(){
		$("#cont").load("html/check_borrowStatus.html");
	})
	//图书续借
	$("#delayBorrow").click(function(){
		$("#cont").load("html/delayBorrow.html");
	})
	$("#student_change").load("html/student_change.html");
	$("#book_num").load("html/book_num.html");
	$("#book_num_change").load("html/book_num_change.html");
	$("#lend_state").load("html/lend_state.html");
	$("#lend_state_change").load("html/lend_state_change.html");
	$("#pass_change").load("html/pass_change.html");
	//增加
	$("#addbook").click(function(){
		$("#cont").load("html/AddBook.html");
	})
	$("#addstu").click(function(){
		$("#cont").load("html/AddStu.html");
	})
	
	//删除
	$("#deletebook").click(function(){
		$("#cont").load("html/DeleteBook.html");
	})
	$("#deletestu").click(function(){
		$("#cont").load("html/DeleteUser.html");
	})
	//通过作者查询图书信息
	$("#search_byAuthor").load("html/search_author.html");
	//学生信息查询
	$("#stu_search").load("html/stu_search.html");
	//借阅记录查询
	$("#loaningRecord").load("html/loaningRecord.html")
	//罚款管理
	$("#penalty").load("html/penalty.html");
	$("#searchById").load("html/search_id.html");
})